#!/usr/bin/env bash

RATE=250
if [ -n "$1" ]; then
  RATE="$1"
fi

say_cancellable() {
  say "$@" &
  pid=$!
  trap "kill -9 $pid" 1 9 2 15
  trap "exit" 3
  while true; do
    finished=$(ps -p $pid | wc -l)
    if [[ "$finished" -eq 1 ]]; then
      break
    fi
    sleep 0.02
  done
}

speak() {
  while read line; do
    voice=$(echo "$line" | cut -d ':' -f 1)
    content=$(echo "$line" | cut -d ':' -f 2-)
    say_cancellable --rate=$RATE -v $voice "$content"
  done
}

url=$(pbpaste)
links -dump "$url" | awk '
  function strip(str) {
    sub(/^ +/, "", str)
    sub(/ +$/, "", str)
    return str
  }

  function next_voice() {
    current_voice = (current_voice % 9) + 1
    return voices[current_voice]
  }

  /submit/ {
    topic = ""
    getline
    while (match($0, /points by/) == 0) {
      topic = topic " " strip($0)
      getline
    }
    print("Alex: Topic is " topic)
  }
  
  /by [^ ]+ [^ ]+ [^ ]+ ago/ { next }

  /[^ ]+ [^ ]+ [^ ]+ ago/ {
    if (!($1 in names)) {
      names[$1] = next_voice()
    }
    sayer_line = names[$1] ": " $1 " says "
    spoken = ""

    getline
    while (match($0, /  reply/) != 1) {
      spoken = spoken " " strip($0)
      getline
    }
    print(sayer_line spoken)
  }

  BEGIN {
    split("Alex Moira Karen Daniel Samantha Tessa Fred Veena Victoria", voices)
    current_voice = 1
  }
' | speak
